---
- name: info vm demo
  hosts: esxi_host
  become: false
  gather_facts: false

  vars:
    vm:
      name: "lcc-tcs-install"

  tasks:
    - name: get vm info
      shell: "vim-cmd vmsvc/getallvms | grep {{ vm.name }}"
      register: vminfo

    - debug: msg="{{ vminfo.stdout }}"
