---

- hosts: all
 # become: true
  tasks:

  #- name: Update redhat repo
  #  yum:  #general package mamnager 
  #    update_cache: yes
  #  when: ansible_distribution == "RedHat"
  - name: copy files to html server
    tags: copy
    copy:
   # unarchieve: this module will just unzip a zip file where src is downloading a zip
      src: site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
      #remote_src: yes when the src is set to something that is not avilable locally


  - name: Install apache, php packages and run update
    tags: apache # tags: apache,db
    package:  #general package mamnager 
      name: 
         - apache2
         - libapache2-mod-php
      state: latest
      update_cache: yes
#    when: ansible_distribution == "Ubuntu" 
    #when: ansible_distribution in ["Ubuntu" , "Debian"] and ansible_version == "8.2"

#- hosts: [blablabla]   you can have multiple of these in the file

 
