---

- hosts: all
  tasks:

  - name: Managing Services (start)
    tags: start
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"

  - name: Managing Services (stop)
    tags: stop
    service:
      name: apache2
      state: stopped
    when: ansible_distribution == "Ubuntu"

  - name: Changing File
    tags: change
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin mubeen@gmail.com
    when: ansible_distribution == "Ubuntu"
    register: httpd  #saving stste of httpd service

  - name: Restarting Service
    tags: change
    service:
      name: httpd
      state: restarted
    when: httpd.changed

